# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 
# Snakefile
import os

# Set up config
configfile: "config/PonAbe_split_migration_jsfs.yaml"
n_train_sims = config["n_train_sims"] # number of simulations for training NPE
n_ensemble = config["n_ensemble"] # number of posterior per round for ensemble training
datadir = config["datadir"] # directory for training data
posteriordir = config["posteriordir"] # output directory for posterior
total_rounds = config["total_rounds"]

# Get the list of rule files
rule_files = [os.path.join("rules/", f) for f in os.listdir("workflow/rules/") if f.endswith(".smk")]

# Include the rule files
for rule in rule_files:
    include: rule

# Define the final target
rule final:
    input:
        expand(os.path.join(datadir, "round_{k}/", "{i}.trees"), i=range(n_train_sims), k=list(range(total_rounds))),
        expand(os.path.join(datadir, "round_{k}/", "theta_{i}.npy"), i=range(n_train_sims), k=list(range(total_rounds))),
        expand(os.path.join(datadir, "round_{k}/", "x_{j}.npy"), j=range(n_train_sims), k=list(range(total_rounds))),
        expand(os.path.join(posteriordir, "round_{k}/", "posterior_{e}.pkl"), k=list(range(total_rounds)), e=range(n_ensemble)),
        expand(os.path.join(posteriordir, "round_{k}/", "ensemble_posterior.pkl"), k=list(range(total_rounds))),
        expand(os.path.join(posteriordir, "round_{k}/", "default_obs_samples.npy"), k=list(range(total_rounds))),
        expand(os.path.join(posteriordir, "round_{k}/", "default_obs_corner.png"), k=list(range(total_rounds))),
        expand(os.path.join(datadir, "round_{k}/", "thetas.npy"), k=list(range(total_rounds))), 
        os.path.join(datadir, "x_obs.npy"),
        os.path.join(datadir, "ts_star.trees")
