datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "moments_LD_stats2"
embedding_net: "CNN"
n_sims : 50000
n_trains : [1e4, 3e4, 5e4]
pops : ["YRI", "CEU"]
n_segs: 10
n_ensemble: 5 # number of ensemble members