datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "tskit_jsfs"
polarised: True
embedding_net: "CNN"
n_sims : 80000
n_trains : [1e3, 3e3, 1e4, 3e4, 5e4, 8e4]
n_ensemble: 10 # number of ensemble members