n_train_sims: 5 # number of simulations per rounds
datadir: "results/AnaPla_split_migration/data/"
posteriordir: "results/AnaPla_split_migration/posterior/"
demog_model: "AnaPla_split_migration"
ts_processor: "dinf_multiple_pops"
n_snps: 2000 # number of SNPs to use (for dinf)
embedding_net: "ExchangeableCNN"
total_rounds: 2 # number of rounds
n_ensemble: 5