n_train_sims: 5000 # number of simulations per rounds
datadir: "results/PonAbe_split_migration_jsfs/data/"
posteriordir: "results/PonAbe_split_migration_jsfs/posterior/"
demog_model: "PonAbe_split_migration"
ts_processor: "tskit_jsfs"
embedding_net: "CNN"
total_rounds: 5 # number of rounds
n_ensemble: 5 # number of ensemble members