datadir: "results/amortized_msprime/AnaPla_2epoch_SPIDNA/data/"
posteriordir: "results/amortized_msprime/AnaPla_2epoch_SPIDNA/posterior/"
demog_model: "AraTha_2epoch"
ts_processor: "dinf_reshape"
embedding_net: "SPIDNA"
n_sims_per_round : 1000
n_rounds : 20
n_ensemble: 10 # number of ensemble members