datadir: "results/amortized_msprime/YRI_CEU/data/"
posteriordir: "results/amortized_msprime/YRI_CEU/posterior/"
demog_model: "YRI_CEU"
ts_processor: "dinf_multiple_pops"
embedding_net: "ExchangeableCNN_OG"
datasubdir: "dinf_CNN_OG_500SNPs"
posteriorsubdir: "dinf_CNN_OG_500SNPs"
n_rep_coverage: 5
n_sims : 5
n_trains : [5]
n_snps : 500
n_ensemble: 1 # number of ensemble members