project_dir: "/sietch_colab/natep/popgensbi/popgensbi_snakemake/YRI_CEU_dinf_new"
demog_model: "YRI_CEU"
ts_processor: "dinf_multiple_pops"
embedding_net: "ExchangeableCNN_OG"
chunk_size: 100 # number of instances to simulate per worker
n_train: 10000
n_test: 1000
n_snps : 1000
n_ensemble: 1 # number of ensemble members
n_rep_coverage: 100
train_npe:
  batch_size: 256 # batch size for training
  learning_rate: 0.0005
  validation_fraction: 0.2
  stop_after_epoch: 20
  clip_max_norm: 5
