executor: slurm
jobs: 10000

default-resources:
  - slurm_partition=kerngpu,kern
  - slurm_account=kernlab
  - mem_mb=4000         # Default memory per job
  - threads=1           # Default threads per job
  - runtime=60          # Default runtime per job
#default-resources:
#  time: 300
#  mem_mb: 12000
#  threads: 1
#restart-times: 3
max-jobs-per-second: 1000
max-status-checks-per-second: 240
local-cores: 4
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True
