# --- top level arguments are ALWAYS REQUIRED --- #

# change this to the project directory you want to use
project_dir: "/sietch_colab/natep/popgensbi_snakemake/recombination_rate"

cpu_resources:
  runtime: "2h"
  mem_mb: 16000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 1
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:1 --constraint=a100"

random_seed: 1
chunk_size: 10 # number of instances to simulate per worker
n_train: 2000
n_val: 1000
n_test: 1000

train_embedding_net_separately: False # train embedding network separately from normalizing flow
use_cache: True # load features into CPU memory
optimizer: "Adam"
batch_size: 64
learning_rate: 0.0001
max_num_epochs: 1000
stop_after_epochs: 1000
clip_max_norm: 5
packed_sequence: False

simulator:
  class_name: "recombination_rate"
  # OPTIONAL CLASS KWARGS:
  sequence_length: 500000
  mutation_rate: 1.5e-8
  pop_size: 4e4
  samples:
    pop_0: 20

processor:
  class_name: "ReLERNN_processor"
  # OPTIONAL CLASS KWARGS:
  n_snps: 2000
  phased: True
  maf_thresh: 0.01

embedding_network:
  class_name: "ReLERNN"
  # OPTIONAL CLASS KWARGS:
  input_size: 40 # num haplotypes
  n_snps: 2000
  output_size: 64
  shuffle_genotypes: True

vcf_prediction:
  vcf: "foo/snp.vcf.gz"
  ancestral_fasta: "foo/anc.fa.gz"
  population_map: "foo/popmap.yaml"
  window_size: 500000
  window_by_variants: False
  min_snps: 1000
