seed: 1024                                        # random seed
path: "/sietch_colab/natep/popgensbi/yri-ceu"     # write stuff here
cpus: 100                                         # number of CPUs for simulation
snps: 2000                                        # number of snps to use
sequence-length: 10000000

samples:                                          # samples per pop
  CEU: 10
  YRI: 10

reps:                                             # number of replicates
  train: 10000
  val: 1000
  test: 1000
  sbi: 10000

model:                                            # neural network stuff
  prefix: "ex-cnn"
  rnn-max-snps: 2000
  optimizer: "AdamW"
  batch-size: 32
  learning-rate: 0.0001
  max-epochs: 1000

prior:                                            # prior, arguments to np.random.Generator
  N_A:
    func: "uniform"
    args:
      low: 100.0
      high: 100000.0

  N_YRI:
    func: "uniform"
    args:
      low: 100.0
      high: 100000.0

  N_CEU_initial:
    func: "uniform"
    args:
      low: 100.0
      high: 100000.0

  N_CEU_final:
    func: "uniform"
    args:
      low: 100.0
      high: 100000.0

  m:
    func: "uniform"
    args:
      low: 0.0
      high: 0.0005

  Tp:
    func: "uniform"
    args:
      low: 0.0
      high: 60000.0

  T:
    func: "uniform"
    args:
      low: 0.0
      high: 60000.0
