# --- top level arguments are ALWAYS REQUIRED --- #

# change this to the project directory you want to use
project_dir: "/sietch_colab/natep/popgensbi_snakemake/AraTha_2epoch"

cpu_resources:
  runtime: "2h"
  mem_mb: 16000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 1
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:1 --constraint=a100"

random_seed: 1
n_chunk: 50 # number of jobs for parallel simulation
n_train: 5000
n_val: 1000
n_test: 1000

train_embedding_net_separately: True # train embedding network separately from normalizing flow
use_cache: True # load features into CPU memory
optimizer: "Adam"
batch_size: 32
learning_rate: 0.0005
max_num_epochs: 200
stop_after_epochs: 20
clip_max_norm: 5
packed_sequence: True

simulator:
  class_name: "AraTha_2epoch"
  # OPTIONAL CLASS KWARGS:
  sequence_length: 1000000
  mutation_rate: 1.5e-8
  recombination_rate: 1.5e-8
  samples:
    SouthMiddleAtlas: 20

processor:
  class_name: "genotypes_and_distances"
  # OPTIONAL CLASS KWARGS:
  max_snps: 10000
  min_freq: 0.00
  max_freq: 0.00

embedding_network:
  class_name: "RNN"
  # OPTIONAL CLASS KWARGS:
  input_size: 21 # num individuals + 1
  output_size: 64

prediction:
  n_chunk: 10
  vcf: "example_data/AraTha_2epoch/snp.vcf.gz"
  ancestral_fasta: "example_data/AraTha_2epoch/anc.fa.gz"
  population_map: "example_data/AraTha_2epoch/popmap.yaml" # subset of samples, with populations
  windows: "example_data/AraTha_2epoch/windows.bed" # windows to predict over
  min_snps_per_window: 100 # filter out low-density windows
