vcf_path: "empirical_prediction/test_data/test.vcf"
output_dir: "empirical_prediction/"

cpu_resources:
  runtime: "2h"
  mem_mb: 16000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 1
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:1 --constraint=a100"


ts_inference:
   window_size: 1000
   window_type: "variant_index"
   report: True
   ancestral_states: "empirical_prediction/test_data/test-AA.npy"
   sample_popns: "empirical_prediction/test_data/test_sample_popns.csv"


chunk_size: 100 # number of instances to process per worker
random_seed: 42

processor:
  class_name: "cnn_extract"
  # OPTIONAL CLASS KWARGS:
  n_snps: 2000
  maf_thresh: 0.05


prediction:
  embedding_net: "AraTha_2epoch_dinf/AraTha_2epoch-cnn_extract-ExchangeableCNN_IN-1-1000-trained_separately/pretrain_embedding_network"
  normalizing_flow: "AraTha_2epoch_dinf/AraTha_2epoch-cnn_extract-ExchangeableCNN_IN-1-1000-trained_separately/pretrain_normalizing_flow"
  batch_size: 100
  use_cache: True
  packed_sequence: False
  simulator:
    class_name: "AraTha_2epoch"
    # OPTIONAL CLASS KWARGS:
    sequence_length: 1000000
    mutation_rate: 1.5e-8
    recombination_rate: 1.5e-8
    samples:
       SouthMiddleAtlas: 10
  
