# --- top level arguments are ALWAYS REQUIRED --- #

# change this to the project directory you want to use
project_dir: "variablepopsize"

cpu_resources:
  runtime: "2h"
  mem_mb: 5000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 20
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:20 --constraint=a100"

random_seed: 1
n_chunk: 2 # number of instances to simulate per worker
n_train: 10000
n_val: 2000
n_test: 2000

train_embedding_net_separately: True # train embedding network separately from normalizing flow
use_cache: True # load features into CPU memory
optimizer: "Adam"
batch_size: 32
learning_rate: 0.0005
max_num_epochs: 200
stop_after_epochs: 20
clip_max_norm: 5
packed_sequence: False

simulator:
  class_name: "VariablePopulationSize"
  # OPTIONAL CLASS KWARGS:
  sequence_length: 2000000
  mutation_rate: 1e-8
  num_time_windows: 21
  max_time: 130000
  time_rate: 0.06
  samples:
    pop0: 25

processor:
  class_name: "tskit_sfs"
  # OPTIONAL CLASS KWARGS:
  window_size: 1_000_000
  span_normalise: False
  polarised: True

embedding_network:
  class_name: "SummaryStatisticsEmbedding"

prediction:
  n_chunk: 10
  vcf: "example_data/VariablePopulationSize/snp.vcf.gz"
  ancestral_fasta: "example_data/VariablePopulationSize/anc.fa.gz"
"workflow/config/variablepopsize.yaml" 61L, 1542B                                                                                                             51,18         66%
