# --- top level arguments are ALWAYS REQUIRED --- #

# change this to the project directory you want to use
project_dir: "/home/adkern/popgensbi_snakemake/variable_popnSize_spidna"

cpu_resources:
  runtime: "2h"
  mem_mb: 16000

gpu_resources: 
  runtime: "4h"
  mem_mb: 50000
  gpus: 1
  slurm_partition: "kerngpu,gpu"
  slurm_extra: "--gres=gpu:1 --constraint=a100"

random_seed: 1
chunk_size: 100 # number of instances to simulate per worker
n_train: 10000
n_val: 1000
n_test: 1000

train_embedding_net_separately: True # train embedding network separately from normalizing flow
use_cache: True # load features into CPU memory
optimizer: "Adam"
batch_size: 32
learning_rate: 0.0005
max_num_epochs: 200
stop_after_epochs: 20
clip_max_norm: 5
packed_sequence: False

simulator:
  class_name: "VariablePopulationSize"
  # OPTIONAL CLASS KWARGS:
  sequence_length: 1000000
  mutation_rate: 1.5e-8
  num_time_windows: 3
  max_time: 100000
  time_rate: 0.1
  samples:
    pop: 10

processor:
  class_name: "SPIDNA_processor"
  # OPTIONAL CLASS KWARGS:
  n_snps: 2000
  maf_thresh: 0.05
  relative_position: True

embedding_network:
  class_name: "SPIDNA_embedding_network"
  # OPTIONAL CLASS KWARGS:
  output_dim: 64
  num_block: 6
  num_feature: 10

